#!/usr/bin/env python

import nbformat
from nbconvert.preprocessors import ExecutePreprocessor

notebook_filename = "Pandas_Overview.ipynb"
notebook_filename_out = "Data_Wrangling.executed.ipynb"


with open(notebook_filename) as f:
    nb = nbformat.read(f, as_version=4)
ep = ExecutePreprocessor(timeout=600, kernel_name='python2')

out = ep.preprocess(nb, {'metadata': {'path': './'}})
with open('executed_file.ipynb', mode='wt') as f:
    nbformat.write(out, f)
